### ISSUE TITLE
Rearchitect page configuration into YAML

### ISSUE THREAD

**Issue by simmerz** [denkGroot/Spina#335]
This will clean up the configuration of pages. It's dependent on #269 really I feel. It'll also make it easier to implement another feature request - unstructured page types.

**Comment by simmerz** [comment]
My suggestion for theme structure:

```yaml
---
structures:
  block_structure:
    title:
      name: Title
      type: Spina::Line
pages:
  - name: Page Name
    description: Some page description
    parts:
      title:
        name: Title
        type: Spina::Line
      content:
        name: Content Blocks
        type: Spina::Structure
        structure:
          title:
            name: Title
            type: Spina::Line
      predefined:
        name: Predefined Type
        type: Spina::Structure
        structure: block_structure
```
