### ISSUE TITLE
Selection custom pages doesn't work

### ISSUE THREAD

**Issue by Qbixx** [denkGroot/Spina#55]
I've used https://gist.github.com/Bramjetten/fdbc1aaf98387595a81b as an example to setup custom pages.

When clicking on the New Page button, only the Blogpost type is visible, you can't slide left or right to a different page type.

**Comment by cybernetlab** [comment]
Looks like all needed markup for slide control are available, but some styles for previous and next icons are missed. As workaround I've created `vendor/assets/stylesheets/spina/admin/application.css.scss` to override spina styles and put there following lines:

```css
@import 'spina';
a.previous:before { content: '<' }
a.next:before { content: '>' }
```
